import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import {
  getFirestore,
  collection,
  doc,
  getDocs,
  setDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  writeBatch,
  onSnapshot,
  query
} from 'firebase/firestore';

// Import Firebase configuration generated by AI Studio
import firebaseConfig from '../../firebase-applet-config.json';

// Initialize Firebase App
const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

// Initialize Firestore with the specific custom database ID
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId || '(default)');

// Initialize Auth
export const auth = getAuth(app);

// Firestore operation types
export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

// Structured error format required by platform diagnostics
export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

// Standard Firestore Error handler
export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Helper to check if a collection is empty
export async function isCollectionEmpty(collectionName: string): Promise<boolean> {
  try {
    const colRef = collection(db, collectionName);
    const snap = await getDocs(query(colRef));
    return snap.empty;
  } catch (err) {
    handleFirestoreError(err, OperationType.GET, collectionName);
  }
}

// Database Seeder
export async function seedDatabase(initialData: {
  products: any[];
  categories: string[];
  addons: any[];
  reviews: any[];
  offers: any[];
  coupons: any[];
  employees: any[];
  customers: any[];
  restaurantInfo: any;
}) {
  try {
    const batch = writeBatch(db);

    // 1. Seed Categories
    const categoriesEmpty = await isCollectionEmpty('categories');
    if (categoriesEmpty) {
      console.log('Seeding categories...');
      for (const cat of initialData.categories) {
        const docRef = doc(collection(db, 'categories'));
        batch.set(docRef, { name: cat });
      }
    }

    // 2. Seed Addons
    const addonsEmpty = await isCollectionEmpty('addons');
    if (addonsEmpty) {
      console.log('Seeding addons...');
      for (const addon of initialData.addons) {
        const docRef = doc(db, 'addons', addon.id);
        batch.set(docRef, addon);
      }
    }

    // 3. Seed Products
    const productsEmpty = await isCollectionEmpty('products');
    if (productsEmpty) {
      console.log('Seeding products...');
      for (const prod of initialData.products) {
        const docRef = doc(db, 'products', prod.id);
        batch.set(docRef, prod);
      }
    }

    // 4. Seed Reviews
    const reviewsEmpty = await isCollectionEmpty('reviews');
    if (reviewsEmpty) {
      console.log('Seeding reviews...');
      for (const rev of initialData.reviews) {
        const docRef = doc(db, 'reviews', rev.id);
        batch.set(docRef, rev);
      }
    }

    // 5. Seed Offers
    const offersEmpty = await isCollectionEmpty('offers');
    if (offersEmpty) {
      console.log('Seeding offers...');
      for (const offer of initialData.offers) {
        const docRef = doc(db, 'offers', offer.id);
        batch.set(docRef, offer);
      }
    }

    // 6. Seed Coupons
    const couponsEmpty = await isCollectionEmpty('coupons');
    if (couponsEmpty) {
      console.log('Seeding coupons...');
      for (const coupon of initialData.coupons) {
        const docRef = doc(db, 'coupons', coupon.id);
        batch.set(docRef, coupon);
      }
    }

    // 7. Seed Employees
    const employeesEmpty = await isCollectionEmpty('employees');
    if (employeesEmpty) {
      console.log('Seeding employees...');
      for (const emp of initialData.employees) {
        const docRef = doc(db, 'employees', emp.id);
        batch.set(docRef, emp);
      }
    }

    // 8. Seed Customers
    const customersEmpty = await isCollectionEmpty('customers');
    if (customersEmpty) {
      console.log('Seeding customers...');
      for (const cust of initialData.customers) {
        const docRef = doc(db, 'customers', cust.id);
        batch.set(docRef, cust);
      }
    }

    // 9. Seed Restaurant Info
    const restInfoEmpty = await isCollectionEmpty('restaurantInfo');
    if (restInfoEmpty) {
      console.log('Seeding restaurant info...');
      const docRef = doc(db, 'restaurantInfo', 'main');
      batch.set(docRef, initialData.restaurantInfo);
    }

    await batch.commit();
    console.log('Database seeding successfully completed.');
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, 'batch-seeding');
  }
}

// Model-specific Firebase operations for Production with secure error reporting
export const dbService = {
  // PRODUCTS
  subscribeProducts: (callback: (products: any[]) => void) => {
    return onSnapshot(collection(db, 'products'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'products');
    });
  },
  saveProduct: async (product: any) => {
    try {
      const docRef = doc(db, 'products', product.id);
      await setDoc(docRef, product, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `products/${product.id}`);
    }
  },
  deleteProduct: async (productId: string) => {
    try {
      const docRef = doc(db, 'products', productId);
      await deleteDoc(docRef);
    } catch (error) {
      handleFirestoreError(error, OperationType.DELETE, `products/${productId}`);
    }
  },

  // CATEGORIES
  subscribeCategories: (callback: (categories: any[]) => void) => {
    return onSnapshot(collection(db, 'categories'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'categories');
    });
  },
  saveCategory: async (category: any) => {
    const colRef = collection(db, 'categories');
    const docRef = category.id ? doc(db, 'categories', category.id) : doc(colRef);
    try {
      await setDoc(docRef, category, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `categories/${category.id || 'new'}`);
    }
  },

  // ADDONS
  subscribeAddons: (callback: (addons: any[]) => void) => {
    return onSnapshot(collection(db, 'addons'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'addons');
    });
  },
  saveAddon: async (addon: any) => {
    try {
      const docRef = doc(db, 'addons', addon.id);
      await setDoc(docRef, addon, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `addons/${addon.id}`);
    }
  },

  // ORDERS
  subscribeOrders: (callback: (orders: any[]) => void) => {
    return onSnapshot(collection(db, 'orders'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'orders');
    });
  },
  saveOrder: async (order: any) => {
    try {
      const docRef = doc(db, 'orders', order.id);
      await setDoc(docRef, order, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `orders/${order.id}`);
    }
  },

  // CUSTOMERS
  subscribeCustomers: (callback: (customers: any[]) => void) => {
    return onSnapshot(collection(db, 'customers'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'customers');
    });
  },
  saveCustomer: async (customer: any) => {
    try {
      const docRef = doc(db, 'customers', customer.id);
      await setDoc(docRef, customer, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `customers/${customer.id}`);
    }
  },

  // REVIEWS
  subscribeReviews: (callback: (reviews: any[]) => void) => {
    return onSnapshot(collection(db, 'reviews'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'reviews');
    });
  },
  saveReview: async (review: any) => {
    try {
      const docRef = doc(db, 'reviews', review.id);
      await setDoc(docRef, review, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `reviews/${review.id}`);
    }
  },

  // OFFERS
  subscribeOffers: (callback: (offers: any[]) => void) => {
    return onSnapshot(collection(db, 'offers'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'offers');
    });
  },
  saveOffer: async (offer: any) => {
    try {
      const docRef = doc(db, 'offers', offer.id);
      await setDoc(docRef, offer, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `offers/${offer.id}`);
    }
  },

  // COUPONS
  subscribeCoupons: (callback: (coupons: any[]) => void) => {
    return onSnapshot(collection(db, 'coupons'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'coupons');
    });
  },
  saveCoupon: async (coupon: any) => {
    try {
      const docRef = doc(db, 'coupons', coupon.id);
      await setDoc(docRef, coupon, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `coupons/${coupon.id}`);
    }
  },

  // EMPLOYEES
  subscribeEmployees: (callback: (employees: any[]) => void) => {
    return onSnapshot(collection(db, 'employees'), (snapshot) => {
      const items: any[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() });
      });
      callback(items);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'employees');
    });
  },
  saveEmployee: async (employee: any) => {
    try {
      const docRef = doc(db, 'employees', employee.id);
      await setDoc(docRef, employee, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, `employees/${employee.id}`);
    }
  },

  // RESTAURANT INFO
  subscribeRestaurantInfo: (callback: (info: any) => void) => {
    return onSnapshot(doc(db, 'restaurantInfo', 'main'), (docSnap) => {
      if (docSnap.exists()) {
        callback(docSnap.data());
      }
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'restaurantInfo/main');
    });
  },
  saveRestaurantInfo: async (info: any) => {
    try {
      const docRef = doc(db, 'restaurantInfo', 'main');
      await setDoc(docRef, info, { merge: true });
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, 'restaurantInfo/main');
    }
  }
};

